// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Pvalue_4by3
double Pvalue_4by3(int q_p, int q_m, int q_r, int q_z, int n_p, int n_m, int n_z, int target_score, double epsilon);
RcppExport SEXP QuaternaryProd_Pvalue_4by3(SEXP q_pSEXP, SEXP q_mSEXP, SEXP q_rSEXP, SEXP q_zSEXP, SEXP n_pSEXP, SEXP n_mSEXP, SEXP n_zSEXP, SEXP target_scoreSEXP, SEXP epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type q_p(q_pSEXP);
    Rcpp::traits::input_parameter< int >::type q_m(q_mSEXP);
    Rcpp::traits::input_parameter< int >::type q_r(q_rSEXP);
    Rcpp::traits::input_parameter< int >::type q_z(q_zSEXP);
    Rcpp::traits::input_parameter< int >::type n_p(n_pSEXP);
    Rcpp::traits::input_parameter< int >::type n_m(n_mSEXP);
    Rcpp::traits::input_parameter< int >::type n_z(n_zSEXP);
    Rcpp::traits::input_parameter< int >::type target_score(target_scoreSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    __result = Rcpp::wrap(Pvalue_4by3(q_p, q_m, q_r, q_z, n_p, n_m, n_z, target_score, epsilon));
    return __result;
END_RCPP
}
// SigPvalue_4by3
double SigPvalue_4by3(int q_p, int q_m, int q_r, int q_z, int n_p, int n_m, int n_z, int target_score, double epsilon, double significance_level);
RcppExport SEXP QuaternaryProd_SigPvalue_4by3(SEXP q_pSEXP, SEXP q_mSEXP, SEXP q_rSEXP, SEXP q_zSEXP, SEXP n_pSEXP, SEXP n_mSEXP, SEXP n_zSEXP, SEXP target_scoreSEXP, SEXP epsilonSEXP, SEXP significance_levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type q_p(q_pSEXP);
    Rcpp::traits::input_parameter< int >::type q_m(q_mSEXP);
    Rcpp::traits::input_parameter< int >::type q_r(q_rSEXP);
    Rcpp::traits::input_parameter< int >::type q_z(q_zSEXP);
    Rcpp::traits::input_parameter< int >::type n_p(n_pSEXP);
    Rcpp::traits::input_parameter< int >::type n_m(n_mSEXP);
    Rcpp::traits::input_parameter< int >::type n_z(n_zSEXP);
    Rcpp::traits::input_parameter< int >::type target_score(target_scoreSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type significance_level(significance_levelSEXP);
    __result = Rcpp::wrap(SigPvalue_4by3(q_p, q_m, q_r, q_z, n_p, n_m, n_z, target_score, epsilon, significance_level));
    return __result;
END_RCPP
}
// domain_4by3
IntegerVector domain_4by3(int q_p, int q_m, int q_r, int q_z, int n_p, int n_m, int n_z);
RcppExport SEXP QuaternaryProd_domain_4by3(SEXP q_pSEXP, SEXP q_mSEXP, SEXP q_rSEXP, SEXP q_zSEXP, SEXP n_pSEXP, SEXP n_mSEXP, SEXP n_zSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type q_p(q_pSEXP);
    Rcpp::traits::input_parameter< int >::type q_m(q_mSEXP);
    Rcpp::traits::input_parameter< int >::type q_r(q_rSEXP);
    Rcpp::traits::input_parameter< int >::type q_z(q_zSEXP);
    Rcpp::traits::input_parameter< int >::type n_p(n_pSEXP);
    Rcpp::traits::input_parameter< int >::type n_m(n_mSEXP);
    Rcpp::traits::input_parameter< int >::type n_z(n_zSEXP);
    __result = Rcpp::wrap(domain_4by3(q_p, q_m, q_r, q_z, n_p, n_m, n_z));
    return __result;
END_RCPP
}
// pmf_4by3
NumericVector pmf_4by3(int q_p, int q_m, int q_r, int q_z, int n_p, int n_m, int n_z, double epsilon);
RcppExport SEXP QuaternaryProd_pmf_4by3(SEXP q_pSEXP, SEXP q_mSEXP, SEXP q_rSEXP, SEXP q_zSEXP, SEXP n_pSEXP, SEXP n_mSEXP, SEXP n_zSEXP, SEXP epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type q_p(q_pSEXP);
    Rcpp::traits::input_parameter< int >::type q_m(q_mSEXP);
    Rcpp::traits::input_parameter< int >::type q_r(q_rSEXP);
    Rcpp::traits::input_parameter< int >::type q_z(q_zSEXP);
    Rcpp::traits::input_parameter< int >::type n_p(n_pSEXP);
    Rcpp::traits::input_parameter< int >::type n_m(n_mSEXP);
    Rcpp::traits::input_parameter< int >::type n_z(n_zSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    __result = Rcpp::wrap(pmf_4by3(q_p, q_m, q_r, q_z, n_p, n_m, n_z, epsilon));
    return __result;
END_RCPP
}
// user_probability_of_score_4by3
double user_probability_of_score_4by3(int target_score, int q_p, int q_m, int q_r, int q_z, int n_p, int n_m, int n_z, double epsilon);
RcppExport SEXP QuaternaryProd_user_probability_of_score_4by3(SEXP target_scoreSEXP, SEXP q_pSEXP, SEXP q_mSEXP, SEXP q_rSEXP, SEXP q_zSEXP, SEXP n_pSEXP, SEXP n_mSEXP, SEXP n_zSEXP, SEXP epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type target_score(target_scoreSEXP);
    Rcpp::traits::input_parameter< int >::type q_p(q_pSEXP);
    Rcpp::traits::input_parameter< int >::type q_m(q_mSEXP);
    Rcpp::traits::input_parameter< int >::type q_r(q_rSEXP);
    Rcpp::traits::input_parameter< int >::type q_z(q_zSEXP);
    Rcpp::traits::input_parameter< int >::type n_p(n_pSEXP);
    Rcpp::traits::input_parameter< int >::type n_m(n_mSEXP);
    Rcpp::traits::input_parameter< int >::type n_z(n_zSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    __result = Rcpp::wrap(user_probability_of_score_4by3(target_score, q_p, q_m, q_r, q_z, n_p, n_m, n_z, epsilon));
    return __result;
END_RCPP
}
